# Railway Nixpacks Configuration for Puppeteer / Chromium
[phases.setup]
nixPkgs = [
    "chromium",
    "libgbm",
    "libxkbcommon",
    "libGL",
    "libatk-bridge2-0",
    "libgtk-3-0",
    "libnss3",
    "libasound2"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
